#!/usr/bin/zsh
# For use by sessionizer scripts.

make_session() {
    session_name=$1
    root_dir=$2
    window_name=$3
    command=$4
    tmux new-session -ds $session_name -c $root_dir -n $window_name $command
    tmux switch-client -t $session_name
}

make_window() {
    window_name=$1
    command=$2
    tmux new-window -dc "#{session_path}" -n $window_name $command
}
