#!/usr/bin/zsh

theme_name=$1

function replace {
    original=$1
    target=$2
    file=$3
    delimiter=$4
    if [[ $delimiter == '' ]]; then
        delimiter='/'
    fi
    sed 's'${delimiter}${original}${delimiter}${target}${delimiter} --in-place ${file}
}

hex_color='#[0-9a-f]\{6\}'

# Yolk templates.
replace 'let theme = "\(dark\|light\)"' 'let theme = "'${theme_name}'"' ~/.config/yolk/theme.rhai
yolk sync

# Background.
feh --bg-scale $(xdg-user-dir PICTURES)/backgrounds/${theme_name}

# Dunst.
dunstctl reload

# Tmux.
tmux source-file ~/.config/tmux/tmux.conf
