#!/usr/bin/zsh

picom='[p]icom'
polybar='p[o]lybar'
autorandr='[a]utorandr'
darkman='[d]arkman'
feh='[f]eh'
selected_option=$(rofi-menu "utilities" $picom $polybar $autorandr $darkman $feh)

case $selected_option in
    $picom)
        toggle-picom
        ;;
    $polybar)
        start-polybar
        ;;
    $autorandr)
        display-config
        ;;
    $darkman)
        darkman toggle
        ;;
    $feh)
        ~/.fehbg
        ;;
esac
