require("config.options")
require("config.keymaps")
require("config.diagnostics")
require("config.autocommands")
require("project-settings.load")
require("config.lazy")
vim.notify(ProjectSettings.notification_text)
