#!/bin/sh

YELLOW="#fabd2fff"
BLUE="#83a598ff"
RED="#fb4934ff"
AQUA="#8ec07cff"
BACKGROUND="#282828ff"
FOREGROUND="#ebdbb2ff"

i3lock \
--insidever-color=$BACKGROUND   \
--ringver-color=$BLUE           \
\
--insidewrong-color=$BACKGROUND \
--ringwrong-color=$RED          \
\
--inside-color=$BACKGROUND      \
--ring-color=$YELLOW            \
--line-color=$FOREGROUND        \
--separator-color=$AQUA         \
\
--verif-color=$AQUA             \
--wrong-color=$RED              \
--time-color=$FOREGROUND        \
--date-color=$FOREGROUND        \
--layout-color=$FOREGROUND      \
--keyhl-color=$AQUA             \
--bshl-color=$RED               \
\
--screen 1                      \
--blur 2                        \
--clock                         \
--indicator                     \
--time-str="%H:%M:%S"           \
--date-str="%A, %Y-%m-%d"       \
--keylayout 1                   \
