#!/usr/bin/zsh

# Kill existing instances.
polybar-msg cmd quit

if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload main &
        echo $m
    done
else
    polybar --reload main &
fi
